// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1i1i7tcKLNbiXq4a27jgaV04y-u2NvOo',
    appId: '1:886408956858:web:5f0051a78098e41556ab83',
    messagingSenderId: '886408956858',
    projectId: 'hotel-booking-system-843ad',
    authDomain: 'hotel-booking-system-843ad.firebaseapp.com',
    storageBucket: 'hotel-booking-system-843ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtN_MSWv5GEqvxF8liOIrtg7J2jHjBUBs',
    appId: '1:886408956858:android:ffcf55c56aa1cd0e56ab83',
    messagingSenderId: '886408956858',
    projectId: 'hotel-booking-system-843ad',
    storageBucket: 'hotel-booking-system-843ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtN_MSWv5GEqvxF8liOIrtg7J2jHjBUBs',
    appId: '1:886408956858:ios:your-ios-app-id',
    messagingSenderId: '886408956858',
    projectId: 'hotel-booking-system-843ad',
    storageBucket: 'hotel-booking-system-843ad.firebasestorage.app',
    iosBundleId: 'com.example.bookingmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtN_MSWv5GEqvxF8liOIrtg7J2jHjBUBs',
    appId: '1:886408956858:ios:your-macos-app-id',
    messagingSenderId: '886408956858',
    projectId: 'hotel-booking-system-843ad',
    storageBucket: 'hotel-booking-system-843ad.firebasestorage.app',
    iosBundleId: 'com.example.bookingmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtN_MSWv5GEqvxF8liOIrtg7J2jHjBUBs',
    appId: '1:886408956858:web:your-windows-app-id',
    messagingSenderId: '886408956858',
    projectId: 'hotel-booking-system-843ad',
    authDomain: 'hotel-booking-system-843ad.firebaseapp.com',
    storageBucket: 'hotel-booking-system-843ad.firebasestorage.app',
  );
}

